apiVersion: v1
kind: Secret
metadata:
    name: {{ include "zeppelin.fullname" . }}-shiro-secret
    namespace: {{ .Release.Namespace }}
    labels:
        {{- include "zeppelin.labels" $ | trim | nindent 4 }}
type: Opaque
stringData:
  shiro.ini: |
    [users]
    dataOps = Tz44828IX60O, admin

    [main]
    sessionManager = org.apache.shiro.web.session.mgt.DefaultWebSessionManager
    cookie = org.apache.shiro.web.servlet.SimpleCookie
    cookie.name = JSESSIONID
    cookie.httpOnly = true
    sessionManager.sessionIdCookie = $cookie
    securityManager.sessionManager = $sessionManager
    securityManager.sessionManager.globalSessionTimeout = 86400000
    shiro.loginUrl = /api/login
    [roles]
    admin = *
    [urls]
    /api/version = anon
    /api/cluster/address = anon
    /api/interpreter/setting/restart/** = authc
    /api/interpreter/** = authc, roles[admin]
    /api/notebook-repositories/** = authc, roles[admin]
    /api/configurations/** = authc, roles[admin]
    /api/credential/** = authc, roles[admin]
    /api/admin/** = authc, roles[admin]
    /** = authc
