{{- $postgresqlDatabase := index .Values "lighter-postgresql" "auth" "database" -}}
{{- $postgresqlUsername := index .Values "lighter-postgresql" "auth" "username" -}}
{{- $postgresqlPassword := index .Values "lighter-postgresql" "auth" "password" -}}
{{- $postgresqlImageTag := index .Values "lighter-postgresql" "image" "tag" | default "postgres:15" -}}
{{- $primaryReadinessInitialDelay := index .Values "lighter-postgresql" "primary" "readinessProbe" "initialDelaySeconds" | default 300 -}}
{{- $primaryLivenessInitialDelay := index .Values "lighter-postgresql" "primary" "livenessProbe" "initialDelaySeconds" | default 300 -}}



kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "lighter.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }} 
  labels:
    {{- include "lighter.labels" $ | trim | nindent 4 }}
  annotations:
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "lighter.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lighter.labels" $ | trim | nindent 4 }}
spec:
  serviceName: {{ include "lighter.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "lighter.fullname" . }}-postgresql
  template:
    metadata:
      labels:
        app: {{ include "lighter.fullname" . }}-postgresql
    spec:
      securityContext:
          runAsGroup: 999 
          runAsUser: 999 
          fsGroup: 999
          fsGroupChangePolicy: OnRootMismatch
      containers:
      - name: {{ include "lighter.fullname" . }}-postgresql
        image: {{ $postgresqlImageTag }}
        securityContext:
              allowPrivilegeEscalation: false
        resources: 
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: POSTGRES_DB
          value: {{ $postgresqlDatabase }}
        - name: POSTGRES_USER
          value: {{ required "Postgresql username required" $postgresqlUsername }}
        - name: POSTGRES_PASSWORD
          value: {{ required "Postgresql password required" $postgresqlPassword }}
        - name: PGDATA                  
          value: /data/pgdata
        ports:
        - containerPort: 5432
        livenessProbe:
            exec:
                command:
                    - /bin/sh
                    - -c
                    - pg_isready -U {{ $postgresqlUsername }} -d {{ $postgresqlDatabase }}
            initialDelaySeconds: {{ $primaryLivenessInitialDelay }}
            periodSeconds: 10
        readinessProbe:
            exec:
                command:
                    - /bin/sh
                    - -c
                    - pg_isready -U {{ $postgresqlUsername }} -d {{ $postgresqlDatabase }}
            initialDelaySeconds: {{ $primaryReadinessInitialDelay }}
            periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
     
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "lighter.fullname" . }}-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighter.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lighter.labels" $ | trim | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: {{ include "lighter.fullname" . }}-postgresql
  selector:
    app: {{ include "lighter.fullname" . }}-postgresql







