name: Build Spark and hive metastore docker images
on:
  release:
    types:
      - released
      
# on:
#   push:
#     paths:
#     - 'installer/charts/hive-metastore/Dockerfile'
#     - 'spark_docker_image/Dockerfile'
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

jobs:
  build_hive:
    strategy:
          matrix:
            include:
              - spark_version: 3.5.1
                hadoop_version: 3.3.4
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Free Up Disk Space
        run: docker system prune -af --volumes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build & Push Hive Metastore
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          file: ./installer/charts/hive-metastore/Dockerfile
          push: true
          tags: ghcr.io/aisingapore/kapitan-spark/hive-metastore:${{ github.event.release.tag_name }}-hadoop3.3.4

  build_spark:
    strategy:
          matrix:
            include:
              - spark_version: 3.5.1
                hadoop_version: 3.3.4
    runs-on: ubuntu-22.04
    needs: build_hive
    steps:
      - uses: actions/checkout@v2
      - name: Free Up Disk Space
        run: docker system prune -af --volumes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build & Push Spark
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          file: ./spark_docker_image/Dockerfile
          push: true
          tags: ghcr.io/aisingapore/kapitan-spark/spark:${{ github.event.release.tag_name }}-spark3.5.1

  build_zeppelin:
    strategy:
          matrix:
            include:
              - spark_version: 3.5.1
                hadoop_version: 3.3.4
    runs-on: ubuntu-22.04
    needs: build_spark
    steps:
      - uses: actions/checkout@v2
      - name: Free Up Disk Space
        run: docker system prune -af --volumes
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build & Push Zeppelin
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64
          file: ./installer/charts/zeppelin/Dockerfile
          push: true
          tags: ghcr.io/aisingapore/kapitan-spark/zeppelin:${{ github.event.release.tag_name }}-spark3.5.1


